# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Knock a Little Harder
description: >- # this means to ignore newlines until "baseurl:"
  Test automation, and perhaps some other things...
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  wei-y
show_excerpts: true
excerpt_separator: "\n\n"

author:
  name: Wei Yang
  bio: QA Tester & Automation Expert

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jemoji

defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: true
      header:
        show_overlay_excerpt: false
        overlay_image: /assets/images/header.jpg
